### ISSUE TITLE
Crash when choosing Show Layout by XML in Demo

### ISSUE THREAD

**Issue by Mailaender** [dockpanelsuite/dockpanelsuite#117]
```
X11 Error encountered: 
  Error: BadMatch (invalid parameter attributes)
  Request:     12 (0)
  Resource ID: 0x2600015
  Serial:      485
  Hwnd:        Hwnd, Mapped:True ClientWindow:0x2600016, WholeWindow:0x2600015, Zombie=False, Parent:[<null>]
  Control:     WeifenLuo.WinFormsUI.Docking.DockPanel, BorderStyle: None   at System.Environment.get_StackTrace() in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/corlib/System/Environment.cs:line 261
   at System.Windows.Forms.XplatUIX11.HandleError(IntPtr display, XErrorEvent ByRef error_event) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUIX11.cs:line 2115
   at System.Windows.Forms.XplatUIX11.XTranslateCoordinates(IntPtr , IntPtr , IntPtr , Int32 , Int32 , Int32 ByRef , Int32 ByRef , IntPtr ByRef )
   at System.Windows.Forms.XplatUIX11.ClientToScreen(IntPtr handle, Int32 ByRef x, Int32 ByRef y) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUIX11.cs:line 2695
   at System.Windows.Forms.XplatUI.ClientToScreen(IntPtr handle, Int32 ByRef x, Int32 ByRef y) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUI.cs:line 525
   at System.Windows.Forms.Control.PointToScreen(Point p) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3844
   at System.Windows.Forms.Control.RectangleToScreen(Rectangle r) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3928
   at WeifenLuo.WinFormsUI.Docking.DockPanel.GetAutoHideWindowBounds(Rectangle rectAutoHideWindow) in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockPanel.AutoHideWindow.cs:line 602
   at WeifenLuo.WinFormsUI.Docking.DockPanel.OnLayout(System.Windows.Forms.LayoutEventArgs levent) in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockPanel.cs:line 682
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.Control affectedControl, System.String affectedProperty) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3822
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ScrollableControl.cs:line 576
   at WeifenLuo.WinFormsUI.Docking.DockPanel.OnVisibleChanged(System.EventArgs e) in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockPanel.cs:line 874
   at System.Windows.Forms.Control.OnParentVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 6166
   at System.Windows.Forms.Control.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 6293
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ScrollableControl.cs:line 578
   at System.Windows.Forms.Form.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:line 2152
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 4789
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:line 2373
   at System.Windows.Forms.Control.set_Visible(Boolean value) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3200
   at System.Windows.Forms.Application.RunLoop(Boolean Modal, System.Windows.Forms.ApplicationContext context) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Application.cs:line 823
   at System.Windows.Forms.Application.Run(System.Windows.Forms.ApplicationContext context) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Application.cs:line 724
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form mainForm) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Application.cs:line 707
   at DockSample.Program.Main() in /home/matthias/Projekte/dockpanelsuite-master/DockSample/Program.cs:line 17

X11 Error encountered: 
  Error: BadMatch (invalid parameter attributes)
  Request:     12 (0)
  Resource ID: 0x26003EE
  Serial:      6097
  Hwnd:        Hwnd, Mapped:True ClientWindow:0x26003EF, WholeWindow:0x26003EE, Zombie=False, Parent:[<null>]
  Control:     WeifenLuo.WinFormsUI.Docking.DockPanel, BorderStyle: None   at System.Environment.get_StackTrace() in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/corlib/System/Environment.cs:line 261
   at System.Windows.Forms.XplatUIX11.HandleError(IntPtr display, XErrorEvent ByRef error_event) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUIX11.cs:line 2115
   at System.Windows.Forms.XplatUIX11.XTranslateCoordinates(IntPtr , IntPtr , IntPtr , Int32 , Int32 , Int32 ByRef , Int32 ByRef , IntPtr ByRef )
   at System.Windows.Forms.XplatUIX11.ClientToScreen(IntPtr handle, Int32 ByRef x, Int32 ByRef y) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUIX11.cs:line 2695
   at System.Windows.Forms.XplatUI.ClientToScreen(IntPtr handle, Int32 ByRef x, Int32 ByRef y) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUI.cs:line 525
   at System.Windows.Forms.Control.PointToScreen(Point p) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3844
   at System.Windows.Forms.Control.RectangleToScreen(Rectangle r) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3928
   at WeifenLuo.WinFormsUI.Docking.DockPanel.GetAutoHideWindowBounds(Rectangle rectAutoHideWindow) in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockPanel.AutoHideWindow.cs:line 602
   at WeifenLuo.WinFormsUI.Docking.DockPanel.OnLayout(System.Windows.Forms.LayoutEventArgs levent) in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockPanel.cs:line 682
   at System.Windows.Forms.Control.PerformLayout(System.Windows.Forms.Control affectedControl, System.String affectedProperty) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3822
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ScrollableControl.cs:line 576
   at WeifenLuo.WinFormsUI.Docking.DockPanel.OnVisibleChanged(System.EventArgs e) in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockPanel.cs:line 874
   at System.Windows.Forms.Control.OnParentVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 6166
   at System.Windows.Forms.Control.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 6293
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ScrollableControl.cs:line 578
   at System.Windows.Forms.Form.OnVisibleChanged(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:line 2152
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 4789
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:line 2373
   at System.Windows.Forms.Control.set_Visible(Boolean value) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 3200
   at System.Windows.Forms.Control.Show() in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 4153
   at DockSample.MainForm.menuItemNewWindow_Click(System.Object sender, System.EventArgs e) in /home/matthias/Projekte/dockpanelsuite-master/DockSample/MainForm.cs:line 408
   at System.Windows.Forms.ToolStripItem.OnClick(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripItem.cs:line 1001
   at System.Windows.Forms.ToolStripMenuItem.OnClick(System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripMenuItem.cs:line 266
   at System.Windows.Forms.ToolStripMenuItem.HandleClick(Int32 mouse_clicks, System.EventArgs e) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripMenuItem.cs:line 538
   at System.Windows.Forms.ToolStripItem.FireEvent(System.EventArgs e, ToolStripItemEventType met) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripItem.cs:line 1778
   at System.Windows.Forms.ToolStrip.OnMouseUp(System.Windows.Forms.MouseEventArgs mea) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStrip.cs:line 970
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(System.Windows.Forms.MouseEventArgs mea) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripDropDown.cs:line 635
   at System.Windows.Forms.Control.WmLButtonUp(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 5279
   at System.Windows.Forms.Control.WndProc(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 5020
   at System.Windows.Forms.ScrollableControl.WndProc(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ScrollableControl.cs:line 651
   at System.Windows.Forms.ToolStrip.WndProc(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStrip.cs:line 1226
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ToolStripDropDown.cs:line 727
   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 228
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(Message ByRef m) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:line 209
   at System.Windows.Forms.NativeWindow.WndProc(IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/NativeWindow.cs:line 240
   at System.Windows.Forms.XplatUIX11.DispatchMessage(MSG ByRef msg) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUIX11.cs:line 3576
   at System.Windows.Forms.XplatUI.DispatchMessage(MSG ByRef msg) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/XplatUI.cs:line 605
   at System.Windows.Forms.Application.RunLoop(Boolean Modal, System.Windows.Forms.ApplicationContext context) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Application.cs:line 941
   at System.Windows.Forms.Application.Run(System.Windows.Forms.ApplicationContext context) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Application.cs:line 724
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form mainForm) in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Application.cs:line 707
   at DockSample.Program.Main() in /home/matthias/Projekte/dockpanelsuite-master/DockSample/Program.cs:line 17

System.NullReferenceException: Object reference not set to an instance of an object
  at System.Windows.Forms.MdiWindowManager.FormClosed (System.Object sender, System.EventArgs e) [0x0001c] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/MdiWindowManager.cs:401 
  at System.Windows.Forms.Form.OnClosed (System.EventArgs e) [0x0001c] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2003 
  at System.Windows.Forms.Form.FireClosedEvents (CloseReason reason) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:159 
  at System.Windows.Forms.Form.RaiseCloseEvents (Boolean last_check, Boolean cancel) [0x00092] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2554 
  at System.Windows.Forms.Form.WmClose (System.Windows.Forms.Message& m) [0x000b8] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2597 
  at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x000c0] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2438 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:228 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000c] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:209 
  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) [0x0008e] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/NativeWindow.cs:240 
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Windows.Forms.MdiWindowManager.FormSizeChangedHandler (System.Object sender, System.EventArgs e) [0x00048] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/MdiWindowManager.cs:167 
  at (wrapper delegate-invoke) <Module>:invoke_void__this___object_EventArgs (object,System.EventArgs)
  at System.Windows.Forms.Control.OnSizeChanged (System.EventArgs e) [0x00029] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:6229 
  at WeifenLuo.WinFormsUI.Docking.DockContent.OnSizeChanged (System.EventArgs e) [0x00056] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContent.cs:331 
  at System.Windows.Forms.Control.UpdateBounds (Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight) [0x000f2] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:4881 
  at System.Windows.Forms.Control.UpdateBounds (Int32 x, Int32 y, Int32 width, Int32 height) [0x00023] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:4842 
  at System.Windows.Forms.Control.SetBoundsCoreInternal (Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) [0x0012c] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:4716 
  at System.Windows.Forms.Control.SetBoundsCore (Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:4662 
  at System.Windows.Forms.Form.SetBoundsCore (Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) [0x00096] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2323 
  at System.Windows.Forms.Control.SetBoundsInternal (Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) [0x000a8] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:4138 
  at System.Windows.Forms.Control.SetBounds (Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) [0x00044] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:4123 
  at System.Windows.Forms.Control.set_Size (Size value) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:3048 
  at System.Windows.Forms.Form.set_Size (Size value) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:1195 
  at System.Windows.Forms.Form.set_FormBorderStyle (FormBorderStyle value) [0x00084] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:710 
  at System.Windows.Forms.Form.set_MdiParent (System.Windows.Forms.Form value) [0x000d5] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:920 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Form:set_MdiParent (System.Windows.Forms.Form)
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetPane (WeifenLuo.WinFormsUI.Docking.DockPane pane) [0x0009f] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:696 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.RemoveFromPane (WeifenLuo.WinFormsUI.Docking.DockPane pane) [0x0000d] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:410 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_PanelPane (WeifenLuo.WinFormsUI.Docking.DockPane value) [0x00053] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:395 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_Pane (WeifenLuo.WinFormsUI.Docking.DockPane value) [0x00054] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:289 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_DockPanel (WeifenLuo.WinFormsUI.Docking.DockPanel value) [0x00012] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:232 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Dispose (Boolean disposing) [0x00008] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:40 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Dispose () [0x00001] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:32 
  at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Form_Disposed (System.Object sender, System.EventArgs e) [0x00001] in /home/matthias/Projekte/dockpanelsuite-master/WinFormsUI/Docking/DockContentHandler.cs:916 
  at System.ComponentModel.Component.Dispose (Boolean release_all) [0x0004f] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/System/System.ComponentModel/Component.cs:134 
  at System.Windows.Forms.Control.Dispose (Boolean disposing) [0x000b9] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:984 
  at System.Windows.Forms.ContainerControl.Dispose (Boolean disposing) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ContainerControl.cs:544 
  at System.Windows.Forms.Form.Dispose (Boolean disposing) [0x00045] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:1986 
  at DockSample.DummyDoc.Dispose (Boolean disposing) [0x0001f] in /home/matthias/Projekte/dockpanelsuite-master/DockSample/DummyDoc.Designer.cs:20 
  at System.ComponentModel.Component.Dispose () [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/System/System.ComponentModel/Component.cs:111 
  at (wrapper remoting-invoke-with-check) System.ComponentModel.Component:Dispose ()
  at System.Windows.Forms.Control.Dispose (Boolean disposing) [0x0009d] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:980 
  at System.ComponentModel.Component.Dispose () [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/System/System.ComponentModel/Component.cs:111 
  at (wrapper remoting-invoke-with-check) System.ComponentModel.Component:Dispose ()
  at System.Windows.Forms.Control.Dispose (Boolean disposing) [0x0009d] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:980 
  at System.Windows.Forms.ContainerControl.Dispose (Boolean disposing) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/ContainerControl.cs:544 
  at System.Windows.Forms.Form.Dispose (Boolean disposing) [0x00045] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:1986 
  at DockSample.MainForm.Dispose (Boolean disposing) [0x0001f] in /home/matthias/Projekte/dockpanelsuite-master/DockSample/MainForm.Designer.cs:20 
  at System.ComponentModel.Component.Dispose () [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/System/System.ComponentModel/Component.cs:111 
  at (wrapper remoting-invoke-with-check) System.ComponentModel.Component:Dispose ()
  at System.Windows.Forms.Form.WmClose (System.Windows.Forms.Message& m) [0x000f0] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2602 
  at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x000c0] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Form.cs:2438 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:228 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000c] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/Control.cs:209 
  at System.Windows.Forms.NativeWindow.WndProc (IntPtr hWnd, Msg msg, IntPtr wParam, IntPtr lParam) [0x0008e] in /home/abuild/rpmbuild/BUILD/mono-3.0.6/mcs/class/Managed.Windows.Forms/System.Windows.Forms/NativeWindow.cs:240 
```

**Comment by DanWBR** [comment]
I got this error in a few other places, all of them related to invalid coordinates (negative values) and/or zeroed widths and heights. Mono seems to set the layout in a crazy order, so when some of these functions are called when the window is about to be shown, the actual dimensions of the window aren't set yet, that's why X11 blames about invalid parameters, probably negative coordinates/dimensions being passed to it.

The solution is to include a check to see if the window/button/rectangle coordinates and dimensions are higher than zero before calling these functions.

I'll try to come up with a structured fix ASAP.

**Comment by NitzanS1** [comment]
> I got this error in a few other places, all of them related to invalid coordinates (negative values) and/or zeroed widths and heights. Mono seems to set the layout in a crazy order, so when some of these functions are called when the window is about to be shown, the actual dimensions of the window aren't set yet, that's why X11 blames about invalid parameters, probably negative coordinates/dimensions being passed to it.
> 
> The solution is to include a check to see if the window/button/rectangle coordinates and dimensions are higher than zero before calling these functions.
> 
> I'll try to come up with a structured fix ASAP.

Can you update how to fix this error?

Thanks

**Comment by DanWBR** [comment]
See https://github.com/DanWBR/dwsim3/commits/master/DockPanelSuite/WinFormsUI/Docking
