### ISSUE TITLE
System.ArgumentException: Rectangle '{X=0,Y=0,Width=0,Height=20}' cannot have a width or height equal to 0.

### ISSUE THREAD

**Issue by bogusfocused** [dockpanelsuite/dockpanelsuite#129]
Bug as described in http://sourceforge.net/p/dockpanelsuite/discussion/402316/thread/48712639

Any fixes for it?

**Comment by smoothdeveloper** [comment]
I'm hitting similar issue in VS2012LightDockPaneStrip.OnPaint in the second place where LinearGradientBrush is instanciated.

I'm working on a fix, the fix involves encapsulating the logic to check the rectangle size before drawing the rectangle with the brush, so it will be easier to replace similar usages in other themes.

    System.ArgumentException: Rectangle '{X=0,Y=0,Width=0,Height=-1}' cannot have a width or height equal to 0.
      at System.Drawing.Drawing2D.LinearGradientBrush..ctor(Rectangle rect, Color color1, Color color2, LinearGradientMode linearGradientMode)
      at WeifenLuo.WinFormsUI.Docking.VS2012LightDockPaneStrip.OnPaint(PaintEventArgs e)
      at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
      at System.Windows.Forms.Control.OnPrint(PaintEventArgs e)
      at System.Windows.Forms.Control.WmPrintClient(Message& m)
      at System.Windows.Forms.Control.WndProc(Message& m)
      at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
      --- End of inner exception stack trace -

**Comment by smoothdeveloper** [comment]
If this gets merged, I would appreciate if a new alpha release could be pushed on nuget.

Thanks
