### ISSUE TITLE
'A generic error occurred in GDI+' During DockWindow Painting

### ISSUE THREAD

**Issue by roken** [dockpanelsuite/dockpanelsuite#25]
This exception has popped up a couple times when running in a terminal services environment (Citrix).  More specific details will be provided if/when the issue can be reproduced.

```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
    at System.Drawing.Graphics.CheckErrorStatus(Int32 status) 
    at System.Drawing.Graphics.DrawRectangle(Pen pen, Int32 x, Int32 y, Int32 width, Int32 height)
    at WeifenLuo.WinFormsUI.Docking.DockWindow.OnPaint(PaintEventArgs e) 
    ...in WeifenLuo.WinFormsUI\Docking\DockWindow.cs:line 128
    at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
    at System.Windows.Forms.Control.WmPaint(Message& m) 
    at System.Windows.Forms.Control.WndProc(Message& m) 
    at System.Windows.Forms.ScrollableControl.WndProc(Message& m) 
    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m) 
    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) 
    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 
```

**Comment by jeffu231** [comment]
I have seen this several times recently over a RDC connection to our app that is using the dock panel. I only see it when using RDC.  I have seen it happen more often when a portion of the window is off the screen, but I am not sure if it is truly related.

**Comment by DaisyDave** [comment]
I can currently reproduce this on a PC running 64bit Windows Server 2008 R2 Standard. It occurs when I close the all forms attached to the DockPanel. I think it's a timing thing as at a customers site there are 2 identical servers, one exhibits the error whilst the other does not, the difference is in the configuration of our software.

I have a patch which I have tested which just catches the exception and ignores it. I will try to create a pull request to fix the problem but this is my first attempt at such a beast.
