### ISSUE TITLE
ArgumentOutOfRangeException:GetVisibleContent & NullReferenceException:EndDrag 

### ISSUE THREAD

**Issue by jlbrownjoey** [dockpanelsuite/dockpanelsuite#290]
Seems to be related to other issues, very hard to replicate on our development system, it happens on our production machines, it seems to be related to things happening in the background when the tab title is select (and held) or switching tabs - running on a touch screen system.

We end up with a big red cross where the tabs should be.

System.ArgumentOutOfRangeException
High ExtraData 01/06/2015 08:58:15  System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
High ExtraData 01/06/2015 08:58:15  Source - WeifenLuo.WinFormsUI.Docking
High ExtraData 01/06/2015 08:58:15  StackTrace-    at WeifenLuo.WinFormsUI.Docking.DockContentCollection.GetVisibleContent(Int32 index),   at WeifenLuo.WinFormsUI.Docking.DockContentCollection.get_Item(Int32 index),   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.TabCollection.get_Item(Int32 index),   at WeifenLuo.WinFormsUI.Docking.VS2005DockPaneStrip.EnsureDocumentTabVisible(IDockContent content, Boolean repaint),   at WeifenLuo.WinFormsUI.Docking.VS2005DockPaneStrip.OnPaint(PaintEventArgs e),   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer, Boolean disposeEventArgs),   at System.Windows.Forms.Control.WmPaint(Message& m),   at System.Windows.Forms.Control.WndProc(Message& m),   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.WndProc(Message& m),   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m),   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m),   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://cloud.githubusercontent.com/assets/12715870/7938473/8b99e13a-093d-11e5-8148-032ea9dae700.png)

Trying to replicate this on my development machine I was able to produce the following exception:
This is using the latest library (2.9.0.0) The other one possibly was using an older version, (2.2.0.0) however I believe this occurs in both versions.
 
System.NullReferenceException
High ExtraData 02/06/2015 12:42:21  System.NullReferenceException: Object reference not set to an instance of an object.
High ExtraData 02/06/2015 12:42:21  Source - WeifenLuo.WinFormsUI.Docking
High ExtraData 02/06/2015 12:42:21  StackTrace-    at WeifenLuo.WinFormsUI.Docking.DockPanel.DragHandlerBase.EndDrag(Boolean abort),   at WeifenLuo.WinFormsUI.Docking.DockPanel.DragHandlerBase.System.Windows.Forms.IMessageFilter.PreFilterMessage(Message& m),   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified),   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg),   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg),   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData),   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context),   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context),   at System.Windows.Forms.Application.Run(ApplicationContext context),   at Ost.Glazer.main.Main(String[] args) in d:\OST\Source\trunk\DotNet\branches\GlazerII\ost.glazer\main.cs:line 122
Low Exception 02/06/2015 12:42:21  Application Closing Due To Unrecoverable Exception In Main Thread

**Comment by roken** [comment]
The ArgumentOutOfRangeException looks to be a duplicate of #209, which has existed essentially since the beginning.

It's hard to say what is causing the second exception, but it could be that the control being dragged loses its parent form.  Without a repro case it will be difficult to identify.

**Comment by jlbrownjoey** [comment]
At the time of writing I wasn't aware I could get the code to debug and investigate.

It's not pretty, but I made a couple of changes to the code to trap and handle the exceptions rather than let the control end up with the red cross of death.

in DockPanel.DragHandler.cs I added a trap to check the form variable is null:

private void EndDrag(bool abort)
            {
                ReleaseHandle();
                Application.RemoveMessageFilter(this);
                Form form = DragControl.FindForm();
                if (form != null) form.Capture = false;

                OnEndDrag(abort);
            }

and in VS2005DockPaneStrip.cs I wrapped the EnsureDocumentTabVisible call with a try catch statement within the OnPaint handler

protected override void OnPaint(PaintEventArgs e)
{
...
try{
                if (EnsureDocumentTabVisible(DockPane.ActiveContent, false))
                    CalculateTabs();
              }catch(Exception ex){
                ex = ex;
              }
...
}
I was able to simulate the exceptions being raised and it in both cases now handles them more gracefully, I accept it's like sticking a plaster on rather than finding the root cause, however it seems to prevent the red cross of death.

I accept the issue is getting it to reliably replicate the issue, believe me I have bashed and clicked dragged and everything else to try and replicate the issues.

If I have any further occurrences I will trap and hopefully be able to give more feedback, but thought my changes might help others with the same issue.

**Comment by lextm** [comment]
In some rare cases, the index parameter can be -1 due to some unknown reasons. I modified `VS2012DockPaneStrip.EnsureDocumentTabVisible` to check against -1. So maybe we should do the same for `VS2005DockPaneStrip`.
