### ISSUE TITLE
System.ComponentModel.Win32Exception: 'Error creating window handle.'

### ISSUE THREAD

**Issue by milsnips** [dockpanelsuite/dockpanelsuite#481]
im getting the above error when i try and display a DockContent form within the dockpanel using the following:

detailForm.Show(dockPanelControl);

I'm running off a SurfacePro3 which has the latest windows insider preview 16170.rs_prerelease.170331-1532.
Same code on other machines with rtm versions of win10 and lower OS versions work fine and don't display this error.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetVisible()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_DockState(DockState value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel)
   at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel)
   at UIHelper.OpenDockWindow(DockContent form, Boolean allowMultipleInstances)
   at MainForm.SwitchOuterPanel(DisplayType type)
   at MainForm.ShowIntroPanel()
   at MainForm.<MainForm_Load>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by lextm** [comment]
Windows Insider builds are unstable, and we don't have plans to support such.

**Comment by milsnips** [comment]
Is it likely that this error would be O/S related? i noticed on some blogs other component providers have had similar issues in the past where user controls would create lots of window handles and not dispose of them properly and they released fixes accordingly. cheers.

**Comment by lextm** [comment]
As .NET Framework 4.7 on Windows 10 does have GDI+ related issues, I assume there is nothing I should do here.
