### ISSUE TITLE
WPF forms host throw null reference exception

### ISSUE THREAD

**Issue by kiebor** [dockpanelsuite/dockpanelsuite#498]
I have created a control library for a visio VSTO using the docking suite as a layout system. The same library is used on a wpf application.

When hosting the dockpanel in wpf via windows forms host, any change to the layout of docked content results in null reference exception. Stack trace from attempted resize of docked content:

System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=WeifenLuo.WinFormsUI.Docking
  StackTrace:
   at WeifenLuo.WinFormsUI.Docking.DockPanel.DragHandlerBase.BeginDrag()
   at WeifenLuo.WinFormsUI.Docking.DockPanel.SplitterDragHandler.BeginDrag(ISplitterDragSource dragSource, Rectangle rectSplitter)
   at WeifenLuo.WinFormsUI.Docking.DockPanel.BeginDrag(ISplitterDragSource dragSource, Rectangle rectSplitter)
   at WeifenLuo.WinFormsUI.ThemeVS2013.VS2013WindowSplitterControl.StartDrag()
   at WeifenLuo.WinFormsUI.Docking.SplitterBase.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at WeifenLuo.WinFormsUI.Docking.SplitterBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at TestHarness.Wpf.Application.Main()

The same embedded control plus methods in winforms application works without issue, likewise in the visio extension.

**Comment by WorksOfLiam** [comment]
I am getting this same issue right now.

Any recommend fixes?
