### ISSUE TITLE
Error on build/run in latest release (2.15)

### ISSUE THREAD

**Issue by cvdevol** [dockpanelsuite/dockpanelsuite#500]
1) Using VS2015
2) set startup project to "DockSample"
3) on Build and run I get the following unhandled exception:

System.ArgumentNullException was unhandled
  HResult=-2147467261
  Message=Buffer cannot be null.
Parameter name: buffer
  ParamName=buffer
  Source=mscorlib
  StackTrace:
       at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
       at WeifenLuo.WinFormsUI.ThemeVS2010.VS2010ThemeBase.VS2010PaletteFactory..ctor(Byte[] file) in C:\Users\Kalki\Downloads\dockpanelsuite-master\WinFormsUI\ThemeVS2010\VS2010ThemeBase.cs:line 51
       at WeifenLuo.WinFormsUI.ThemeVS2010.VS2010ThemeBase..ctor(Byte[] resources) in C:\Users\Kalki\Downloads\dockpanelsuite-master\WinFormsUI\ThemeVS2010\VS2010ThemeBase.cs:line 18
       at WeifenLuo.WinFormsUI.Docking.VS2010BlueTheme..ctor() in C:\Users\Kalki\Downloads\dockpanelsuite-master\WinFormsUI\ThemeVS2010\VS2010BlueTheme.cs:line 13
       at DockSample.MainForm.InitializeComponent() in C:\Users\Kalki\Downloads\dockpanelsuite-master\DockSample\MainForm.Designer.cs:line 107
       at DockSample.MainForm..ctor() in C:\Users\Kalki\Downloads\dockpanelsuite-master\DockSample\MainForm.cs:line 25
       at DockSample.Program.Main() in C:\Users\Kalki\Downloads\dockpanelsuite-master\DockSample\Program.cs:line 17
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by lextm** [comment]
VS2010 is not a working theme. It should be completely removed.

Fixed in 38cab75e6a66b4f0ba8deadeb9cb7eed8c207569

**Comment by cvdevol** [comment]
That's odd. I never had any problems with it in previous releases.

**Comment by lextm** [comment]
Some recent PRs might have triggered the issue, but overall it would be best to remove that theme so as to permanently get rid of any future issues.

**Comment by cvdevol** [comment]
OK. Anyway, it doesn't seem to have any features that other themes don't have.
