### ISSUE TITLE
InvalidOperationException - rectangle calculation must happen first

### ISSUE THREAD

**Issue by jonreis** [dockpanelsuite/dockpanelsuite#516]
I received the following exception. It does not seem to happen often as I cannot seem to reproduce it.

I am using version 3.0.1 of the library.

Main|Microsoft Windows NT 6.2.9200.0|Application Unhandled Exception.
[InvalidOperationException] rectangle calculation must happen first
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.Tab.get_Rectangle()
   at WeifenLuo.WinFormsUI.Docking.VS2012DockPaneStrip.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)|

**Comment by lextm** [comment]
We can only work on an issue when it can be reproduced in a certain way. So let's just track it here and hope some time in the future we find a way to reproduce it.

**Comment by jonreis** [comment]
No problem. I thought you might have an idea how VS2012DockPaneStrip.OnMouseMove might be called before the DockPaneStripBase.Tab.Rectangle gets set.

In my build I have set DockPaneStripBase.Tab._rect = new Rectangle(); to prevent it from being null in the first place.

**Comment by thetemplar** [comment]
I have the same problem.
How exactly did you do the workaround with `DockPaneStripBase.Tab._rect = new Rectangle(); `?
I get protection errors if I try to do that (but I use the dll from nuget).

**Comment by csantav** [comment]
See Issue #522 to reproduce the error
