### ISSUE TITLE
InvalidOperationException("rectangle calculation must happen first");

### ISSUE THREAD

**Issue by csantav** [dockpanelsuite/dockpanelsuite#522]
Steps to reproduce:

1) No documents open
2) move the mouse to where the tab of a new document would appear.
3) use ALT-Key to open a new document via the menu while leaving the mouse where the tab would appear
4) Exception: InvalidOperationException("rectangle calculation must happen first");

- the rectangle was never calculated since the tab was not drawn yet

**Comment by Progress1** [comment]
Sometime i have the same issue - rectangle calculation must happen first (on start or exit application)
I think problem start  appear 3.0 -> 3.0.1 when was rewritten functionality Tabs[index].Rectangle.Value -> GetTabRectangle(index) ? (just guess)

 ```
  at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.Tab.get_Rectangle() in D:\dockpanelsuite-Release_3.0.1\WinFormsUI\Docking\DockPaneStripBase.cs:line 60
   at WeifenLuo.WinFormsUI.ThemeVS2013.VS2013DockPaneStrip.OnMouseMove(MouseEventArgs e) in D:\dockpanelsuite-Release_3.0.1\WinFormsUI\ThemeVS2013\VS2013DockPaneStrip.cs:line 1308
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at WeifenLuo.WinFormsUI.Docking.DockPaneStripBase.WndProc(Message& m) in D:\dockpanelsuite-Release_3.0.1\WinFormsUI\Docking\DockPaneStripBase.cs:line 298
```

Line numbers maybe don't match due personal modification.

**Comment by lextm** [comment]
Duplicate to #516
