### ISSUE TITLE
VS2013DockPane OnPaint Null Reference

### ISSUE THREAD

**Issue by joshjje** [dockpanelsuite/dockpanelsuite#533]
Not sure on how to reproduce, it happens occasionally.  Ill update with more info if I find more.

Reproduced again, DockPanel appears to be null.  I believe I was docking/undocking fairly fast, but this is happening in normal usage as well.

Call Stack
Object reference not set to an instance of an object.
   at WeifenLuo.WinFormsUI.ThemeVS2013.VS2013DockPane.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at WeifenLuo.WinFormsUI.Docking.DockPane.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lextm** [comment]
Hope that you can capture a crash dump. That would give us more data to analyze.

In the meantime, what is the version number you use?

**Comment by joshjje** [comment]
I cant give a crash dump as its for work.  I was able to disassemble and debug it, catching it in the act, and DockPanel was null.  I didnt fully investigate when and how that is null, but I think it may have been after a close/dispose or just rapid dock transitions.  Since its a paint I think it would be reasonable to just wrap all that in null checks.  Its not a big problem yet, but it has been occurring here and there immediately after rolling out to users.

**Comment by joshjje** [comment]
The version used was 3.0.3

**Comment by joshjje** [comment]
We found some code that may have been the culprit that was setting the DockPanel to null on form close.  The OnPaint should still guard against it being null, but ill reopen if that was not in fact the problem.  

Thanks.
