### ISSUE TITLE
Exception Rectangle '{X=0,Y=0,Width=0,Height=20}' cannot have a width or height equal to 0.

### ISSUE THREAD

**Issue by jantje85** [dockpanelsuite/dockpanelsuite#545]
I'm randomly getting the exception shown below when calling Show() to add a new DockContent with DockState DockRightAutoHide.
I'm getting the exception every once in a while doing the exact same thing, sometimes it causes an exception but in most situations it just works. When the exception is cought, all side tab strips fail to render, they show large red crosses.

I did some searching and it seems similar issues were previously reported (bug #129 ), but should have been fixed years ago and i'm on the latest version. In commit f7ec4acb0b1f396e81e33dac1acf78c227605f51 those issues seemed to be addressed via a SafelyDrawLinearGradient which draws a rectangle, but I noticed that commit didn't add any safeguards to calls  to FillPath which also uses a LinearGradientBrush.

Would creating a new DrawingRoutines for filling paths solve this issue without major side effects?
I'm not sure how it's possible for the width to be 0 on some calls... would such a fix simply avoid the exception, but still leave the strips incorrectly drawn?

Exception Rectangle '{X=0,Y=0,Width=0,Height=20}' cannot have a width or height equal to 0.

   at System.Drawing.Drawing2D.LinearGradientBrush..ctor(Rectangle rect, Color color1, Color color2, LinearGradientMode linearGradientMode)
   at WeifenLuo.WinFormsUI.Docking.VS2005AutoHideStrip.DrawTab(Graphics g, TabVS2005 tab)
   at WeifenLuo.WinFormsUI.Docking.VS2005AutoHideStrip.DrawTabStrip(Graphics g, DockState dockState)
   at WeifenLuo.WinFormsUI.Docking.VS2005AutoHideStrip.DrawTabStrip(Graphics g)
   at WeifenLuo.WinFormsUI.Docking.VS2005AutoHideStrip.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by lextm** [comment]
VS2003/2005 themes are too old, as linear gradients are no longer popular. You probably should consider switching to a modern theme instead.

I also made a new commit b9e958c7b98d7838b183493191acfb9744f65fd8 which might fix more potential issues.

**Comment by jantje85** [comment]
Thanks for the update.
I've switched to the VS2015 light theme and we've noticed no exceptions anymore so it seems to indeed be specific to the old theme...
