### ISSUE TITLE
Could not load type ContextMenu

### ISSUE THREAD

**Issue by stigzler** [dockpanelsuite/dockpanelsuite#691]
Hi. Firstly, excited to see this resurrected + thanks to the team keeping this alive. 

I suspect this is something to do with the latest .net/Framework version loosing .ContextMenu, but my dev situations a little complicated. I'm developing a plugin for an app developed in .net Core 3 (I think). I'm developing the plugin in Framework 4.8. All runs fine until I try adding dockpanelsuite. I then get the error:

Could not load type 'System.Windows.Forms.ContextMenu' from assembly 'System.Windows.Forms, Version=4.0.0.0

I tried downgrading to previous Framework versions, but this didn't seem to fix it (albeit weirdly, the .Forms version stayed at 4.0, so I didn't really try too hard as bit fed up at this point). Not sure if it's to do with he native codebase for the parent app, or my plugin's framework. I'm jst wondering if there's anything I can do, as I'm guessing dockpanelsuite is built using a .net version that has .contextmenu still as a memeber?

The full error + stack trace:

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Windows.Forms.ContextMenu' from assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=WeifenLuo.WinFormsUI.Docking
  StackTrace:
   at WeifenLuo.WinFormsUI.Docking.DockPane.get_TabPageContextMenu()
   at WeifenLuo.WinFormsUI.Docking.DockPane.get_HasTabPageContextMenu()
   at WeifenLuo.WinFormsUI.Docking.DockPaneCaptionBase.get_HasTabPageContextMenu()
   at WeifenLuo.WinFormsUI.Docking.VS2012DockPaneCaption.SetButtons()
   at WeifenLuo.WinFormsUI.Docking.VS2012DockPaneCaption.OnRefreshChanges()
   at WeifenLuo.WinFormsUI.Docking.DockPaneCaptionBase.RefreshChanges()
   at WeifenLuo.WinFormsUI.Docking.DockPane.RefreshChanges(Boolean performLayout)
   at WeifenLuo.WinFormsUI.Docking.DockPane.RefreshChanges()
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.RefreshDockPane(DockPane pane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetDockState(Boolean isHidden, DockState visibleState, DockPane oldPane)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.set_DockState(DockState value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState)
   at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel, DockState dockState)
   at stigzler.Launchbox.Gearbox.Presentation.Views.Forms.MainView..ctor() in C:\Users\stigz\source\repos\0.MyCode\CS\Framework\stigzler.Launchbox.GearBox\stigzler.Launchbox.Gearbox.Presentation\Views\Forms\MainView.cs:line 34
   at stigzler.Launchbox.Gearbox.Presentation.Controllers.Launch.MainView() in C:\Users\stigz\source\repos\0.MyCode\CS\Framework\stigzler.Launchbox.GearBox\stigzler.Launchbox.Gearbox.Presentation\Controllers\MainController.cs:line 30
   at stigzler.Launchbox.GearBox.Services.Controllers.HookController.RegisterHookCommunication(HookType hookType) in C:\Users\stigz\source\repos\0.MyCode\CS\Framework\stigzler.Launchbox.GearBox\stigzler.Launchbox.GearBox.Services\Controllers\HookController.cs:line 38
   at stigzler.Launchbox.GearBox.Services.PluginHooks.SystemMenuItem.OnSelected() in C:\Users\stigz\source\repos\0.MyCode\CS\Framework\stigzler.Launchbox.GearBox\stigzler.Launchbox.GearBox.Services\PluginHooks\SystemMenuItem.cs:line 26
   at Unbroken.LaunchBox.Windows.Desktop.ContextMenus.ToolsMenu.<>c__DisplayClass8_2.ManageMetaContext(Object )
   at Unbroken.LaunchBox.Windows.Desktop.ContextMenus.ToolsMenu.<>c__DisplayClass8_2.ValidateNotificationWatcher(Object sender, RoutedEventArgs args)

**Comment by lextm** [comment]
You will have to develop the extension on .NET Core as well, because the DPS NuGet package ship different assemblies inside (two for .NET Framework and the other for .NET Core) and they do expose different API surface (conditional compilation).  That can trigger issues like that.

BTW, this repo is no longer actively maintained if you #663.
