### ISSUE TITLE
Collection was modified error when having a floating Window and try to Dock

### ISSUE THREAD

**Issue by diagraph-de** [dockpanelsuite/dockpanelsuite#706]
Object reference not set to an instance of an object.

   at WeifenLuo.WinFormsUI.Docking.DockPanel.DockDragHandler.TestDrop()
   at WeifenLuo.WinFormsUI.Docking.DockPanel.DockDragHandler.OnDragging()
   at WeifenLuo.WinFormsUI.Docking.DockPanel.DragHandlerBase.System.Windows.Forms.IMessageFilter.PreFilterMessage(Message& m)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at aDesign2.Program.Application_ThreadException(Object sender, ThreadExceptionEventArgs e) in C:\Users\d.frede\Projekte\git\aDesign\aDesign\Program.cs:line 97

Solution will be (in FloatWindow.cs):

        internal bool IsDockStateValid(DockState dockState)
        {
            foreach (DockPane pane in NestedPanes)
                foreach (IDockContent content in pane.Contents)
                    if (!DockHelper.IsDockStateValid(dockState, content.DockHandler.DockAreas))
                        return false;

            return true;
        }

        protected override void OnActivated(EventArgs e)
        {
            DockPanel.FloatWindows.BringWindowToFront(this);
            base.OnActivated (e);
            // Propagate the Activated event to the visible panes content objects
            for (var index = 0; index < VisibleNestedPanes.Count; index++)
            {
                var pane = VisibleNestedPanes[index];
                foreach (IDockContent content in pane.Contents)
                    content.OnActivated(e);
            }
        }

**Comment by lextm** [comment]
Can you create a pull request?
